changelog:
- author: themanyfaceddemon
  changes:
  - Добавлена автоматическая система создания ченджлогов
  - Добавлено отображение авторов
  date: '2024-06-02'
  version: 0.0.3
- author: themanyfaceddemon
  changes:
  - Все changelogs написанные руками были утеряны из-за ручной генерации changelog.
  - Теперь changelogs по правде могут быть собраны сразу. Ей.
  date: '2024-06-02'
  version: 0.0.3
