[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-package]
isort = "*"

[packages]
aiofiles = "*"
colorlog = "*"
discord.py = "*"
flask = "*"
flask-socketio = "*"
imageio = "*"
nuitka = "*"
pyzipper = "*"
pyyaml = "*"
requests = "*"

[package]
name = "dm_bot"

[requires]
python_version = "3.11"
