[[source]]
name = "DM_Bot"

[packages]
aiofiles = "*"
colorlog = "*"
discord.py = "*"
flask = "*"
flask-socketio = "*"
imageio = "*"
isort = "*"
nuitka = "*"
pyzipper = "*"
pyyaml = "*"
requests = "*"

[requires]
python_version = "3.11"
