"Changes: Code":
- all:
  - changed-files:
      - any-glob-to-any-file: ['Code/**', 'Prototype/factory_mappings.yml']
      - any-glob-to-all-files: ['!Code/api/**',]

"Changes: API":
- changed-files:
  - any-glob-to-any-file: ['Code/api/**']

"Changes: Sprites":
- changed-files:
  - any-glob-to-any-file: ['Sprites/**']

"Changes: Prototypes":
- all:
  - changed-files:
      - any-glob-to-any-file: ['Prototype/**']
      - all-globs-to-all-files: ['!Prototype/factory_mappings.yml']

"Changes: Docs":
- changed-files:
  - any-glob-to-any-file: ['README.md', 'LICENSE.md', 'Docs/**', 'Libriary_Of_Ruina/**']

"Changes: Unit test":
- changed-files:
  - any-glob-to-any-file: ['Tests/**']

"Changes: Workflows":
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**']

"Changes: Workflows config":
- changed-files:
  - any-glob-to-any-file: ['.github/workflows_config/**']

"Changes: GitHub template":
- changed-files:
  - any-glob-to-any-file: ['.github/ISSUE_TEMPLATE/**', '.github/PULL_REQUEST_TEMPLATE.md']

"Update: Changelog":
- changed-files:
  - any-glob-to-any-file: ['changelog.yml']

"Update: Changelog config":
- changed-files:
  - any-glob-to-any-file: ['updater_config.json']
