"Changes: Code":
- all:
  - changed-files:
      - any-glob-to-any-file: ['Code.DM-Bot/**']
      - all-globs-to-all-files: ['!Code.DB-Bot/bot/**', '!Code.DM-Bot/templates/**', '!Code.DM-Bot/static/**', '!Code.DM-Bot/html/**']

"Changes: Bot":
- changed-files:
  - any-glob-to-any-file: ['Code.DB-Bot/bot/**']

"Changes: UI":
- changed-files:
  - any-glob-to-any-file: ['Code.DM-Bot/templates/**', 'Code.DM-Bot/static/**', 'Code.DM-Bot/html/**']

"Changes: Sprites":
- changed-files:
  - any-glob-to-any-file: ['Sprites.DM-Bot/**']

"Changes: Prototypes":
- changed-files:
  - any-glob-to-any-file: ['Prototype.DM-Bot/**']

"Changes: Locale":
- changed-files:
  - any-glob-to-any-file: ['Loc.DM-Bot/**']

"Changes: Docs":
- changed-files:
  - any-glob-to-any-file: ['README.md', 'LICENSE.md', 'Docs.DM-Bot/**', 'Libriary_Of_Ruina - DB/**']

"Changes: Workflows":
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**', '.github/workflows_config/**']
