"Changes: Code":
- all:
  - changed-files:
      - any-glob-to-any-file: ['Code/**', 'Prototype/class_mappings.yml']
      - all-globs-to-any-file: ['!Code/bot/**', '!Code/templates/**', '!Code/static/**', '!Code/py_html/**']

"Changes: Bot":
- changed-files:
  - any-glob-to-any-file: ['Code/bot/**']

"Changes: UI":
- changed-files:
  - any-glob-to-any-file: ['Code/templates/**', 'Code/static/**', 'Code/py_html/**']

"Changes: Sprites":
- changed-files:
  - any-glob-to-any-file: ['Sprites/**']

"Changes: Prototypes":
- all:
  - changed-files:
      - any-glob-to-any-file: ['Prototype/**']
      - all-globs-to-all-files: ['!Prototype/class_mappings.yml']

"Changes: Locale":
- changed-files:
  - any-glob-to-any-file: ['Loc/**']

"Changes: Docs":
- changed-files:
  - any-glob-to-any-file: ['README.md', 'LICENSE.md', 'Docs/**', 'Libriary_Of_Ruina/**']

"Changes: Unit test":
- changed-files:
  - any-glob-to-any-file: ['Tests/**']

"Changes: Workflows":
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/**']

"Changes: Workflows config":
- changed-files:
  - any-glob-to-any-file: ['.github/workflows_config/**']

"Update: Changelog":
- changed-files:
  - any-glob-to-any-file: ['changelog.yml', 'updater_config.json']
