name: Close PRs on master

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'master' || github.head_ref == 'main' }}

    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: |
          Похоже, вы новичок в нашем репозитории и пытаетесь внести изменения из ветки master.

          Пожалуйста, прочитайте следующие гайды для правильной работы с репозиторием:
          - [Подготовка окружения](https://github.com/AngelsAndDemonsDM/DM-Bot/wiki/Подготовка-окружения)
          - [Как начать работу с репозиторием](https://github.com/AngelsAndDemonsDM/DM-Bot/wiki/Как-начать-работу-с-репозиторием)
          - [Первые изменения](https://github.com/AngelsAndDemonsDM/DM-Bot/wiki/Первые-изменения)

          Данный pull request будет закрыт, так как вы пытаетесь внести изменения из ветки master вашей локальной копии репозитория в ветку master основного репозитория. В будущем, пожалуйста, создавайте отдельные ветки для ваших изменений.
