name: Close PRs on master

on:
  pull_request:
    branches:
      - master
    
jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{github.head_ref == 'master' || github.head_ref == 'main'}}
    
    steps:    
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Вы не можете использовать ветку master для внесения изменений в репозиторий. \n\n Пожалуйста, создайте новую ветку для вашей работы. Вы можете сделать это, выполнив команду `git branch <название_ветки>` и переместив ваши изменения из ветки master."
