name: "Set labels for PR"
on: pull_request

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/labeler@v3
            with:
              configuration-path: .github/labeler.config.yml
              sync-labels: true
