name: "Set labels for PR"
on: 
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/labeler@v5
        configuration-path: .github/workflows_config/labeler.yml
        sync-labels: true
