name: "Set labels for PR"
on: 
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set labels
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/workflows_config/labeler.yml
          sync-labels: true
