name: "Labels for PR"

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Remove unneeded labels
      uses: peter-evans/remove-labels@v2
      with:
        labels: |
          "Changes: Code"
          "Changes: Bot"
          "Changes: UI"
          "Changes: Sprites"
          "Changes: Prototypes"
          "Changes: Locale"
          "Changes: Docs"
        remove-conditions: always
