name: "Label new issues with 'Not sorted'"
on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
    - name: Label new issues with "Not sorted"
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            labels: ["Issue: Not sorted"]
          });
