name: Ping and Assign
on:
  issues:
    types: [opened]

jobs:
  ping_and_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Ping user and assign
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const assignees = ['themanyfaceddemon'];
            const issueNumber = issue.number;
            const repo = context.repo.owner + '/' + context.repo.repo;
            
            await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: assignees
            });

            const body = `@${assignees[0]}, вы были назначены исполнителем этой задачи.`;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: body
            });
